bigquery_copy_dataset: # this needs to match the profile: in your dbt_project.yml file
  target: London_To_Australia
  outputs:
    London_To_Australia:
      type: bigquery
      method: oauth
      project: dataflow-pubsub-django # Replace this with your project id
      dataset: test_AU # Replace this with dbt_your_name, e.g. dbt_bob
      threads: 1
      timeout_seconds: 300
      location: australia-southeast1
      priority: interactive
    Australia_To_London:
      type: bigquery
      method: oauth
      project: dataflow-pubsub-django # Replace this with your project id
      dataset: test_London # Replace this with dbt_your_name, e.g. dbt_bob
      threads: 1
      timeout_seconds: 300
      location: australia-southeast1
      priority: interactive